### PR TITLE
Snapshot testing

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by mysticmind** [comment]
In my local tests are all passing but on CI it fails, I think the issue in terms of difference could be newline chars since the source html uses `Environment.NewLine` and the new line char stored in the file may not match if the verified files got added in a different OS.

**Comment by SimonCropp** [comment]
if that is the case, it is a bug in Verify. i will look into it

**Comment by SimonCropp** [comment]
ok i know what the issue is.

**Comment by mysticmind** [comment]
I am also planning to add an enhancement to support markdown output with carriage returns as configured by the user. In this case, we will need to do unit tests based on what is configured which tests the converter outputs.

**Comment by SimonCropp** [comment]
i think the build is working now

**Comment by mysticmind** [comment]
@SimonCropp I am planning to add a link to https://github.com/VerifyTests/Verify and https://www.youtube.com/watch?v=uGVogEltSkY in the readme so that contributors can understand how snapshot testing works.

**Pull request merged**
