### PR TITLE
Fix Issue #61: Html from Outlook 2016 not being converted to Markdown

### PR DESCRIPTION
**Pull request by janis-veinbergs**
Excess comment removal removed closing style tag. Fix comment removal logic.

### CODE REVIEW

**Comment by janis-veinbergs** [comment]
Don't merge yet - after a while I'll see if HtmlAgilityPack can be used to remove comments. If I won't succeed there, I'd still like set max timeout for Regex matching. Not yet qualified enough to determine if that regex `<!--(\n|.)*?-->` qualifies for potential [catashrophic backtracking](https://www.rexegg.com/regex-explosive-quantifiers.html), but using timeout values is a [best practice](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices#use-time-out-values).

**Comment by mysticmind** [comment]
I haven't reviewed the changes as yet, will wait for further update from you.

**Comment by janis-veinbergs** [comment]
@mysticmind alright, it is actually a piece of cake to remove comments without using regex. Just registered `#comment` node within `Drop` converter and way we go.

Except test is failing (which is good, because brings attention to changing behavior) - previously incomplete comments (without closing `-->` tag) were not removed. HtmlAgilitypack behavior seems better to me, because it identifies incomplete comment and treats everything that follows just like that - a comment. It more accurately resembles browser behavior which will also ignore everything after unclosed comment tag.

@PromoFaux seems to have initially implemented the comment ignoring logic. @PromoFaux, do you have a use case where RemoveComments should not remove unclosed comment or it was just the easy thing to do given comments were being removed using regex?

**Comment by janis-veinbergs** [comment]
@mysticmind any feedback? Don't let the 1 failing check scare you :) I think that test with unclosed comment should be adjusted and the correct behavior would be to remove unclosed comment too.

**Comment by mysticmind** [comment]
@janis-veinbergs can we try to remove comment using HtmlAgilityPack rather than regex, see code snippet below:
```
doc.DocumentNode.Descendants()
 .Where(n => n.NodeType == HtmlAgilityPack.HtmlNodeType.Comment)
 .ToList()
 .ForEach(n => n.Remove());
```

**Comment by janis-veinbergs** [comment]
@mysticmind pull request ready

**Comment by mysticmind** [comment]
@janis-veinbergs thank you, merged the PR!

**Comment by mysticmind** [comment]
@janis-veinbergs quick note, I will plan to release 3.11.0 by start of next week.

**Comment by PromoFaux** [comment]
@janis-veinbergs Sorry for the late reply, I saw the ping whilst out and then forgot to come back!

It was such a long time ago now that I don't really recall my reasoning, I suspect you are right re:the simplest thing to do.

**Pull request merged**
